apiVersion: batch/v1
kind: Job
metadata:
  name: liquibase-migration
spec:
  template:
    spec:
      containers:
      - name: liquibase
        image: faroukelrey19008/backend:latest
        command: ["liquibase"]
        args:
          [
            "--defaultsFile=/liquibase/liquibase.properties",
            "update"
          ]
      restartPolicy: Never

